### ISSUE TITLE
How to handle multiple quizzes/workbooks in a learning module?

### ISSUE THREAD

**Issue by skbt** [boffti/fin_lit#6]
In the learning module 1, we have 2 quizzes and 3 workbooks. And there are two buttons for each quiz. And one button for a workbook.

In the module 2 there are 7 workbooks and 1 quiz.

How should we proceed for handling this? Should we do a button for each?

Or should we combine all the quizzes and all the workbooks into a drop down list with each item being a button?

Or something else?

**Comment by boffti** [comment]
No just add the entry in the DB in module_quiz table. That will create the buttons.
